import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const locales = ['en', 'pl']

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: ReactNode
  params: { locale: string }
}

export default function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  if (!locales.includes(locale)) {
    throw new Error(`Invalid locale: ${locale}`)
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
